// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// planaritytest
SEXP planaritytest(SEXP N, SEXP rows, SEXP cols);
RcppExport SEXP MEGENA_planaritytest(SEXP NSEXP, SEXP rowsSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type N(NSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cols(colsSEXP);
    __result = Rcpp::wrap(planaritytest(N, rows, cols));
    return __result;
END_RCPP
}
